### ISSUE TITLE
swagger.json fails schema validation

### ISSUE THREAD

**Issue by KevinSheedy** [sendgrid/sendgrid-swagger#4]
When trying to use `swagger.json` with an instance of swagger ui, I get the following error:
 
    {
        "messages": [
            "attribute definitions.global:empty_request.properties is missing",
            "attribute definitions.global:id.properties is missing"
        ],
        "schemaValidationMessages": [
            {
                "domain": "validation",
                "instance": {
                    "pointer": "/paths/~1api_keys/get/responses/200"
                },
                "keyword": "oneOf",
                "level": "error",
                "message": "instance failed to match exactly one schema (matched 0 out of 2)",
                "schema": {
                    "loadingURI": "http://swagger.io/v2/schema.json#",
                    "pointer": "/definitions/responseValue"
                }
            }
        ]
    }
 
To reproduce, browse to the [public swagger ui instance](http://petstore.swagger.io/) and copy in the [rawgit url for swagger.json](https://rawgit.com/sendgrid/sendgrid-swagger/master/swagger.json). An error message will appear on the bottom right of the screen.

**Comment by IvanGoncharov** [comment]
It's a problem with [validator-badge](https://github.com/swagger-api/validator-badge) used in `public swagger-ui instance` that you pointed.
Because `properties` isn't mandatory field, and it looks like this already fixed: https://github.com/swagger-api/swagger-parser/pull/165
So it will be fixed in the next release.

**Disclaimer**: I don't have any relation to `swagger-ui`, `validator-badge` or `SendGrid`.
Just working as API consultant and constantly experiencing exactly the same problem.

**Comment by thinkingserious** [comment]
Thanks @IvanGoncharov!

I'll go ahead and close this ticket then.

BTW, I refreshed our swagger doc to be the latest version. If you were looking to create a working mock server with our swagger, I suggest you check out http://stoplight.io/prism.

Have a great day!

**Comment by IvanGoncharov** [comment]
@thinkingserious Thank you, for sharing Swagger spec for your API.
I have little bit unusual usage scenario for your spec, but I will open a separate issue to discuss it.

**Comment by thinkingserious** [comment]
Awesome, we would love to hear about. Thanks!
